In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
x =  iris.data
y = iris.target

<h3>Generate Random Data points(k) </h3>

In [3]:
def random_datapoints(x  , y , k , iters):
    
    for i in range(iters):
        random_values = np.random.randint(0 , len(x) , size = k )
        labels = []
        for randoms in random_values:
            labels.append(y[randoms])
        if len(set(labels)) == len(random_values):
            break
    return np.array(random_values)

<h3>Euclidean Distance</h3>

In [4]:
def euclidean_dist(x_train , x_test , y , random_values):
    
    dists = {}
    for i in random_values:
        dist = np.sqrt(np.square(np.sum((x_test - x_train[i]))))
        dists[dist] =  y[i]
    label = dists[min(dists.keys())]
    
    return label

<h3>kNN</h3>

In [5]:
def kNN(x_train , x_test , y_train , k = 2, iters = 50):
    pred_y = []
    for i in np.arange(0 , len(x_test)):
        random_data_points = random_datapoints(x_train , y_train , k = k , iters = iters)
        label = euclidean_dist(x_train , x_test[i] , y_train , random_values = random_data_points)
        pred_y.append(label)
    return pred_y

In [6]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , 
                                                       test_size = 0.3 , 
                                                       random_state = 123)

In [7]:
pred_y =  kNN(x_train = x_train , x_test = x_test , y_train = y_train , k = 3 , iters = 100 )

In [8]:
from sklearn.metrics import confusion_matrix , accuracy_score
print(confusion_matrix( y_test ,pred_y))
print(accuracy_score( y_test ,pred_y)) 

[[18  0  0]
 [ 1  8  1]
 [ 0  4 13]]
0.866666666667
